apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:postgresql://postgresql-db-instance.cdom0oqg86u4.eu-west-2.rds.amazonaws.com:5432/restaurantdb
  foodcataloguedb_url: jdbc:postgresql://postgresql-db-instance.cdom0oqg86u4.eu-west-2.rds.amazonaws.com:5432/foodcataloguedb
  userdb_url: jdbc:postgresql://postgresql-db-instance.cdom0oqg86u4.eu-west-2.rds.amazonaws.com:5432/userdb
  orderdb_url: mongodb+srv://admin:Welcome17@cluster0.exwviw5.mongodb.net/orderdb?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  